name: Go

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

permissions:
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      - run: go mod tidy
      - run: go build -v ./...
      - run: go test -v ./...
      - name: Save test results
        if: always()
        run: echo "Tests completed"

  benchmark:
    needs: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      - name: Find Pull Request
        id: find_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/pulls" \
          | jq '.[0].number')
          if [ "$PR_NUMBER" == "null" ]; then
            echo  "prExists=false" >> $GITHUB_ENV
          else
            echo  "prExists=true" >> $GITHUB_ENV
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          fi
      - name: Run Go Bench (current branch)
        if: env.prExists == 'true'
        run: go test -count=10 -cpu=1,2,4 -benchmem -run=^$ -bench ^*$ ./... > bench-current.txt
      - name: Upload benchmark results
        if: env.prExists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: bench-current
          path: app/bench-current.txt
      - name: Checkout main branch
        if: env.prExists == 'true'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Run Go Bench (main branch)
        if: env.prExists == 'true'
        run: go test -count=10 -cpu=1,2,4 -benchmem -run=^$ -bench ^*$ ./... > bench-main.txt
      - name: Upload benchmark results
        if: env.prExists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: bench-main
          path: app/bench-main.txt

  analyze-and-comment:
    needs: benchmark
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: bench-current
          path: app/
      - uses: actions/download-artifact@v4
        with:
          name: bench-main
          path: app/
      - run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH
      - run: |
          benchstat main=bench-main.txt current=bench-current.txt > result.txt
          cat result.txt
      - run: |
          benchresult=$(cat result.txt | jq -Rs .)
          curl -X POST 'https://openaigh-ggcze4eygjf8a2az.eastus-01.azurewebsites.net/Bench' -H 'accept: text/plain' -H 'Content-Type: application/json' -d "{\"benchresult\": $benchresult}" > opencomment.md
          cat opencomment.md
      - name: Create PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -s result.txt -a -s opencomment.md ]; then
            COMMENT_BODY=$(echo -e "## Resultados do Benchmark\n\n\`\`\`\n$(cat result.txt)\n\`\`\`\n\n## Análise do resultado\n\n$(cat opencomment.md)")
            echo "$COMMENT_BODY" > comment_body.md
            gh pr comment $PR_NUMBER --body "$(cat comment_body.md)"
          fi